### ISSUE TITLE
Newly added variables are not in the proper order

### ISSUE THREAD

**Issue by plytki** [OkaeriPoland/okaeri-configs#26] opened 2022-02-15 00:19 UTC
Newly added variables are not in proper order

1. Create configuration file with configurer presented below.
2. Add new variable to your config class.
3. Update your config.

Your newly added variables won't be placed in order as you initialized them in your config class.

All libs are versioned in 3.4.2.

```
ConfigManager.create(PluginConfiguration.class, (it) -> {
            it.withConfigurer(new OkaeriValidator(new YamlBukkitConfigurer(SectionSeparator.NEW_LINE), true), new SerdesBukkit());
            it.withBindFile(pluginConfigurationFile);
            it.saveDefaults();
            it.load(true);
        });
```

**Comment by PinkLolicorn** [comment] 2022-02-15 00:34
`4.0.0-beta6`

Reproduced in:
- yaml-bukkit
- yaml-bungee
- yaml-snakeyaml
- hjson
- json-gson

Cannot reproduce:
- hocon-lightbend

Not applicable:
- json-simple

**Comment by plytki** [comment] 2022-03-04 23:25
What is the ETA for the bug fix?

**Comment by PinkLolicorn** [comment] 2022-03-05 01:29
No specific ETA due to non-critical nature of the issue. No time to spare for this specific issue at the moment. Pull requests and other contributions are welcome.

**Comment by PinkLolicorn** [comment] 2022-05-29 17:05
Fixed in https://github.com/OkaeriPoland/okaeri-configs/commit/735057e309bcfd9bfea3f7846b129d8d29957e9e (`4.0.0-beta21`). Sorting is performed pre-save only, so `Configurer#getAllKeys` and similar can be out-of-order.

**Closed by PinkLolicorn** 2022-05-29 17:05 UTC
Labels: bug
